id: P010365
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB35090
  title: གསོ་རིག་རྒྱུད་བཞིའི་བྲིས་ཆ་ངོ་མཚར་མཐོང་བ་དོན་ལྡན
  author: ''
  volumes:
    540f2d84fe0848428b7f1605cc934d40:
      image_group_id: I1PD37760
      title: ''
      volume_number: 1
      total_pages: 528
